.editorconfig
src/app/apiclients/apiclient.js
src/app/apiclients/cache.js
src/app/apiclients/ghost.js
src/app/apiclients/github.js
src/app/apiclients/twitter.js
src/app/carloscuesta.js
src/app/data/static.js
src/app/routes.js
src/app/routes/about.js
src/app/routes/cache.js
src/app/routes/index.js
src/app/templates/_includes/_sections/_education.pug
src/app/templates/_includes/_sections/_experience.pug

- Standard code style.
- Refactor staticData

🎨 Standard code style

---

.editorconfig
.gitignore
README.md
package.json
scripts/sitemap/README.md
scripts/sitemap/blog.js
scripts/sitemap/index.js
scripts/sitemap/pages.js
yarn.lock

Generate sitemaps.xml on build time

Generate sitemaps on build

---

package.json
src/utils/api/blog/__tests__/__snapshots__/ghost.spec.js.snap
src/utils/api/blog/index.js
src/utils/theme/theme.css
yarn.lock

✨ Link blog post headings

---

src/__tests__/_app/__snapshots__/_app.spec.js.snap
src/components/pages/index/Biography/__tests__/__snapshots__/biography.spec.js.snap
src/components/pages/index/Biography/index.js
src/components/pages/index/Biography/styles.module.css
src/components/pages/index/SectionTitle/styles.module.css
src/components/shared/BlogPost/styles.module.css
src/pages/404/styles.module.css
src/pages/_app.js
src/utils/theme/theme.css

As Avenir Next has more weights and provides a more consistent rendering on Chrome, Safari and Firefox, specially for bold weights

💄 Use Avenir Next

---

.flowconfig
.gitignore
.lighthouserc.js
.travis.yml
package.json
yarn.lock

This PRs configures Lighthouse-CI as a Github Check in order to test website pages on every pull request, to audit performance.
To see the results of the tests take a look at the Pull-Request checks:

🔧 Setup Lighthouse–CI

---

package.json

Since I'm not using server rendering. I can use `next export` to improve speed since all the website is SSG 
https://nextjs.org/docs/advanced-features/static-html-export

🔧 Use next export on build script

---

.gitignore
package.json
src/components/pages/index/Writings/index.js
src/components/shared/BlogPost/index.js
src/pages/blog/index.js
src/pages/index/index.js
src/utils/api/blog/__tests__/__snapshots__/blog.spec.js.snap
src/utils/api/blog/index.js
src/utils/api/blog/mutators.js

When using `fetchPosts` I was sending 3 attributes that were not needed for rendering the posts:
- `html`
- `disqusIdentifier`
- `dateModified`
Specially the `html` is a really big string that contains the whole content of the post useful for rendering the detail but not the preview posts. 
I removed those attributes and I reduced the size of the page from `98kb` to `24kb` ⚡. That's a great improvement 🎉
Look at the comparison between a build on production and localhost

⚡️ Optimize ssg pageProps for posts data

---

src/__tests__/blog/[slug]/__snapshots__/slug.spec.js.snap
src/pages/blog/[slug]/index.js

🐛 Blog post og:image meta

---

package.json
src/utils/api/blog/index.js
yarn.lock

This allows me to generate table of contents for any post automatically ❤️

✨ Add remark-toc

---

src/components/pages/index/Biography/__tests__/__snapshots__/biography.spec.js.snap
src/components/pages/index/Biography/index.js

:pencil2: Update bio grammar

---

package.json
src/utils/api/blog/index.js
yarn.lock

As of https://github.com/carloscuesta/carloscuesta.me/commit/2b26ca950aeb0381393b3a76e223a48ac94d669e, remark-parse moved the `gfm` into as a separate package see https://github.com/remarkjs/remark/pull/536

✨ Use remark-gfm

---

src/components/shared/Layout/NavigationMenu/Hamburger/styles.module.css
src/components/shared/Layout/NavigationMenu/MenuLink/styles.module.css
src/components/shared/Layout/NavigationMenu/index.js
src/components/shared/Layout/NavigationMenu/styles.module.css
src/components/shared/Layout/__tests__/__snapshots__/layout.spec.js.snap
src/utils/theme/theme.css

Improve the site Navigation Header.
Things that has been done:

💄 Improve site header

---

src/components/shared/Layout/Footer/index.js
src/components/shared/Layout/Footer/styles.module.css
src/components/shared/Layout/__tests__/__snapshots__/layout.spec.js.snap

A small redesign of the footer.

💄 Improve site footer

---

src/components/pages/index/Biography/__tests__/__snapshots__/biography.spec.js.snap
src/components/pages/index/Biography/index.js
src/components/pages/index/Biography/styles.module.css

Improve and add more information to the Home biography section.

💄 Improve Biography home component

---

src/components/pages/index/OpenSource/Project/styles.module.css
src/components/shared/BlogPost/styles.module.css
src/components/shared/Layout/NavigationMenu/MenuLink/styles.module.css
src/components/shared/Layout/NavigationMenu/styles.module.css
src/utils/theme/theme.css

Increase `b` and `strong` tags font-weight and update the links style.

💄 Adjust theme Typography

---

package.json
src/components/pages/index/Writings/ScrollButtons/index.js
src/components/pages/index/Writings/ScrollButtons/styles.module.css
src/components/pages/index/Writings/__tests__/__snapshots__/writings.spec.js.snap
src/components/pages/index/Writings/__tests__/stubs.js
src/components/pages/index/Writings/__tests__/writings.spec.js
src/components/pages/index/Writings/index.js
src/components/pages/index/Writings/styles.module.css
yarn.lock

Improve the UX of Writings scroll-buttons.

🚸  Improve Writings scroll buttons UX

---

src/__tests__/about/__snapshots__/about.spec.js.snap
src/__tests__/blog/__snapshots__/blog.spec.js.snap
src/components/pages/about/Education/__tests__/__snapshots__/education.spec.js.snap
src/components/pages/about/Experience/__tests__/__snapshots__/experience.spec.js.snap
src/components/pages/about/ItemTitle/__tests__/__snapshots__/itemTitle.spec.js.snap
src/components/pages/about/ItemTitle/index.js
src/components/pages/about/ItemTitle/styles.module.css
src/components/pages/about/WhoAmI/__tests__/__snapshots__/whoAmI.spec.js.snap
src/components/pages/about/WhoAmI/index.js
src/components/pages/blog/Year/__tests__/__snapshots__/year.spec.js.snap
src/components/pages/blog/Year/index.js
src/components/pages/blog/Year/styles.module.css
src/components/pages/index/Biography/__tests__/__snapshots__/biography.spec.js.snap
src/components/pages/index/Biography/index.js
src/components/pages/index/Contact/__tests__/__snapshots__/contact.spec.js.snap
src/components/pages/index/Header/__tests__/__snapshots__/header.spec.js.snap
src/components/pages/index/Header/index.js
src/components/pages/index/OpenSource/Project/index.js
src/components/pages/index/OpenSource/Project/styles.module.css
src/components/pages/index/OpenSource/__tests__/__snapshots__/openSource.spec.js.snap
src/components/pages/index/Writings/__tests__/__snapshots__/writings.spec.js.snap
src/components/shared/BlogPost/__tests__/__snapshots__/blogPost.spec.js.snap
src/components/shared/BlogPost/index.js
src/components/shared/BlogPost/styles.module.css
src/components/shared/PageTitle/__tests__/__snapshots__/pageTitle.spec.js.snap
src/components/shared/PageTitle/index.js
src/components/shared/SectionTitle/__tests__/__snapshots__/sectionTitle.spec.js.snap
src/components/shared/SectionTitle/index.js
src/components/shared/SectionTitle/styles.module.css

Refactor the `hX` usage over the whole website.

♻️ Improve heading-levels usage

---

src/components/shared/Layout/__tests__/layout.spec.js

Test the open/close of the Hamburger menu.

✅ Increase Layout - Hamburger coverage

---

src/components/pages/about/Education/__tests__/__snapshots__/education.spec.js.snap
src/components/pages/about/Experience/__tests__/__snapshots__/experience.spec.js.snap
src/components/pages/index/Contact/__tests__/__snapshots__/contact.spec.js.snap
src/components/pages/index/OpenSource/__tests__/__snapshots__/openSource.spec.js.snap
src/components/pages/index/OpenSource/index.js
src/components/pages/index/Writings/__tests__/__snapshots__/writings.spec.js.snap
src/components/pages/index/Writings/index.js
src/components/pages/opensource/Repositories/__tests__/__snapshots__/repositories.spec.js.snap
src/components/pages/opensource/Stats/__tests__/__snapshots__/stats.spec.js.snap
src/components/shared/SectionTitle/__tests__/__snapshots__/sectionTitle.spec.js.snap
src/components/shared/SectionTitle/__tests__/sectionTitle.spec.js
src/components/shared/SectionTitle/__tests__/stubs.js
src/components/shared/SectionTitle/index.js
src/components/shared/SectionTitle/styles.module.css

✨ Add viewAllLink to SectionTitle

---

src/pages/_document.js

Not using at all the `analytics.js` features, so it makes sense to switch to minimal-analytics to avoid loading the script and improve the performance a little bit

⚡️ Switch to minimal analytics

---

src/utils/api/blog/index.js

🐛 Add `allowDangerousHtml` on remark and rehype for Blog posts

---

package.json
src/__tests__/blog/[slug]/__snapshots__/slug.spec.js.snap
src/components/pages/blog/[slug]/Header/__tests__/__snapshots__/header.spec.js.snap
src/components/pages/blog/[slug]/Header/__tests__/stubs.js
src/components/pages/blog/[slug]/Header/index.js
src/components/pages/blog/[slug]/Header/styles.module.css
src/pages/blog/[slug]/index.js
src/utils/api/blog/__tests__/__snapshots__/blog.spec.js.snap
src/utils/api/blog/mutators.js
yarn.lock

✨ Add reading time into Blog Post detail

---

package.json
public/prism/prism.css
src/utils/theme/theme.css
yarn.lock

Improve Blog posts Prism theme. I ported `sprinkles-syntax` to Prism 🚀 
This is related with #374

💄Improve blog code blocks highlighting

---

src/__tests__/uses/__snapshots__/uses.spec.js.snap
src/__tests__/uses/uses.spec.js
src/components/pages/uses/Section/__tests__/__snapshots__/section.spec.js.snap
src/components/pages/uses/Section/__tests__/section.spec.js
src/components/pages/uses/Section/__tests__/stubs.js
src/components/pages/uses/Section/index.js
src/components/pages/uses/Section/styles.module.css
src/components/pages/uses/SetupImage/__tests__/__snapshots__/setupImage.spec.js.snap
src/components/pages/uses/SetupImage/__tests__/setupImage.spec.js
src/components/pages/uses/SetupImage/index.js
src/components/pages/uses/SetupImage/styles.module.css
src/pages/uses/index.js

Fixes https://github.com/carloscuesta/carloscuesta.me/issues/367

✨ Introduce `/uses` page

---

src/components/pages/blog/[slug]/ShareLinks/__tests__/__snapshots__/shareLinks.spec.js.snap
src/components/pages/blog/[slug]/ShareLinks/index.js

✏️ Fix enjoyed typo

---

.github/workflows/ci.yml
package.json

⬆️ Bump node to `16`

---

package.json
src/utils/api/blog/index.js
src/utils/theme/theme.css
yarn.lock

Add a wrapper on top of the tables so we can make it scroll without breaking the layout.

💄Adjust `table` elements in blog posts for mobile UI

---

src/posts/using-generators-to-improve-developer-productivity.md
src/utils/api/blog/__tests__/__snapshots__/blog.spec.js.snap

Adding a new post to the blog 🤓

📝 Add code generators post

---

src/posts/effective-refactoring-with-codemods.md
src/utils/api/blog/__tests__/__snapshots__/blog.spec.js.snap

Hey! 👋🏼 
This PR adds an article to the blog

📝 Add `Effective Refactoring with Codemods` blog post

---

src/posts/react-miami-2023.md
src/utils/api/blog/__tests__/__snapshots__/blog.spec.ts.snap
tailwind.config.js

📝 Add React Miami 2023 post

---

.gitignore
.vscode/settings.json
next-env.d.ts
package.json
src/app/api/views/[slug]/route.ts
src/app/blog/[slug]/components/Header/ViewsCount/index.tsx
src/app/blog/[slug]/components/Header/__tests__/__snapshots__/header.spec.tsx.snap
src/app/blog/[slug]/components/Header/__tests__/stubs.ts
src/app/blog/[slug]/components/Header/index.tsx
src/app/blog/[slug]/page.tsx
yarn.lock

Hey! 👋🏼 
This PR implements blog page view counts with Vercel KV and React Server Components.

✨ Add `views` count to `/blog/[slug]`

---

jest.config.js
src/app/api/views/[slug]/route.ts
src/app/api/views/__tests__/formatViews.spec.ts
src/app/api/views/formatViews.ts
src/app/api/views/route.ts
src/app/blog/[slug]/components/Header/index.tsx
src/app/blog/components/Post/__tests__/__snapshots__/post.spec.tsx.snap
src/app/blog/components/Post/index.tsx
src/components/ViewsCount/index.tsx

Hey! 👋🏼 
This PR adds blog view counts using `@vercel/kv` to persist the data and `swr`.

✨ Add blog view counts in list and detail

---

.github/workflows/ci.yml
src/app/api/views/[slug]/route.ts
src/app/api/views/__tests__/formatViews.spec.ts
src/app/api/views/formatViews.ts
src/app/api/views/route.ts
src/app/blog/components/Post/__tests__/__snapshots__/post.spec.tsx.snap
src/app/blog/components/Post/__tests__/post.spec.tsx
src/app/blog/components/Post/index.tsx
src/app/blog/page.tsx
src/components/ViewsCount/index.tsx
src/utils/api/blog/__tests__/views.spec.ts
src/utils/api/blog/views.ts

Hey! 👋🏼 
This PR pre-renders the blog post page views to provide a better UX.

✨ Pre-render blog post page views

---

src/app/layout.tsx
src/utils/theme/theme.css
vercel.json

Hey! 👋🏼 
This PR loads the webfont used at the site using `next/fonts` instead of doing it manually.

♻️ Load fonts using `next/font`

---

src/app/about/components/WhoAmI/__tests__/__snapshots__/whoAmI.spec.tsx.snap
src/app/about/components/WhoAmI/index.tsx
src/app/blog/[slug]/components/FeaturedImage/__tests__/__snapshots__/featuredImage.spec.tsx.snap
src/app/blog/[slug]/components/FeaturedImage/index.tsx
src/app/home/components/Writings/BlogPost/__tests__/stubs.ts
src/app/home/components/Writings/BlogPost/index.tsx
src/app/home/components/Writings/__tests__/__snapshots__/writings.spec.tsx.snap
src/app/home/components/Writings/index.tsx

Hey! 👋🏼 
This will improve the LCP on some pages where we're lazy loading above the fold images.

⚡️ Avoid lazyloading above the fold images

---

package.json
yarn.lock

Hey! 👋🏼 
This PR updates Next to 13.4.3.

⬆️ Bump `next` to 13.4.3

---

jest.config.js
package.json
public/mockServiceWorker.js
src/app/blog/[slug]/opengraph-image.tsx
src/app/blog/[slug]/page.tsx
yarn.lock

Hey! 👋🏼 
This PR is related with #1226. We're generating dynamic open graph images for the blog posts, that will look similar to this:
> ![image](https://github.com/carloscuesta/carloscuesta.me/assets/7629661/82487ac8-0a07-476d-8cdf-9209a667ab9d)
The great thing about them is that the information will be automatically updated every minute!
> ![image](https://github.com/carloscuesta/carloscuesta.me/assets/7629661/3051918d-0012-4066-8215-2dc15eabc220)
> ![image](https://github.com/carloscuesta/carloscuesta.me/assets/7629661/b2c0ac1f-6b08-410d-bb59-bac499c4dae3)

✨ Generate opengraph images for `/blog/[slug]`

---

src/posts/shipping-react-native-apps-with-fastlane.md

`brew cask` is no longer a `brew` command. 
Edit the code to use `brew <command> --cask` instead.

edit the brew install command

---

src/app/blog/components/Post/__tests__/post.spec.tsx
src/app/blog/components/Post/__tests__/stubs.ts
src/app/blog/components/Post/index.tsx
src/app/blog/page.tsx
src/app/home/components/Writings/BlogPost/__tests__/stubs.ts
src/app/home/components/Writings/__tests__/stubs.ts
src/utils/api/blog/__tests__/__snapshots__/blog.spec.ts.snap
src/utils/api/blog/__tests__/blog.spec.ts
src/utils/api/blog/index.ts
src/utils/api/blog/mutators.ts

Follow up to: https://github.com/carloscuesta/carloscuesta.me/pull/1367, strangely in the preview environment `dynamic = error` was working properly but when deployed to `master` it started to fail.

♻️ Render `/blog` as a static page

---

.github/workflows/ci.yml

Hey! 👋🏼 
This PR automatically reads the node-version file in GitHub Actions from a source of truth.

🔧 Get `node-version` from file in CI

---

src/app/blog/[slug]/opengraph-image.tsx

Hey! 👋🏼 
The CDN urls were removed and therefore the og image was not being generated as expected.

🐛 Fix `/blog/[slug]` opengraph image

---

src/posts/writing-rfcs.md
src/utils/api/blog/__tests__/__snapshots__/blog.spec.ts.snap

Hey! 👋🏼 
Adding a new post to the blog

📝 Add `Writing RFCs` blog post

---

package.json
pnpm-lock.yaml
src/app/blog/rss.xml/route.ts

Hey! 👋🏼 
This PR adds a feed for the blog

✨ Add `rss` feed for `/blog`

---

src/utils/api/blog/__tests__/__snapshots__/blog.spec.ts.snap
src/utils/api/blog/index.ts
src/utils/api/blog/mutators.ts

Hey! 👋🏼 
This PR removes some fields that are not used anymore as of #1448 
N/A

🔥 Remove unused fields from `PostPreview`

---

package.json
pnpm-lock.yaml
src/app/layout.tsx

♻️ Use `@vercel/speed-insights` package

---

next.config.js
src/app/about/components/Online/__tests__/__snapshots__/online.spec.tsx.snap
src/app/about/components/Online/index.tsx
src/app/about/page.tsx
src/app/home/index.tsx
src/components/Layout/Footer/index.tsx
src/components/Layout/__tests__/__snapshots__/layout.spec.tsx.snap

Hey! 👋🏼 
This PR adds redirects for social profiles.

✨ Use redirects for social profiles

---

.github/workflows/ci.yml
package.json
pnpm-lock.yaml

Replacing the codecov module with the new uploader

♻️ Use `codecov` uploader

---

src/posts/building-server-driven-uis.md
src/posts/composing-uis-with-finite-state-machines.md
src/posts/react-miami-2023.md
src/posts/react-native-meets-codepush.md
src/posts/scalable-react-components-architecture.md
src/utils/theme/theme.css

Hey!  👋🏼 
Adjusting embedded tags in markdown articles.

♻️ Improve articles embedded tags

---

next.config.mjs
src/utils/theme/theme.css
tailwind.config.js

Hey! 👋🏼 
This PR updates the inline `code` block styles

💄 Update inline `code` blocks style

---

next.config.mjs
package.json
pnpm-lock.yaml
src/app/blog/[slug]/components/Playground/index.tsx
src/app/blog/[slug]/components/SandpackCSS/index.tsx
src/app/blog/[slug]/layout.tsx
src/mdx-components.tsx
src/utils/theme/theme.css

✨ Add `Playground` MDX Component

---

next-env.d.ts
src/app/home/components/Biography/__tests__/__snapshots__/biography.spec.tsx.snap
src/app/home/components/Biography/index.tsx
src/app/home/components/Writings/BlogPost/__tests__/__snapshots__/blogPost.spec.tsx.snap
src/app/home/components/Writings/BlogPost/index.tsx
src/app/home/components/Writings/__tests__/__snapshots__/writings.spec.tsx.snap
src/app/home/components/Writings/index.tsx

Hey! 👋🏼 
This PR updates the header contents and the writing styles.

✨ Update header and writings style

---

src/posts/automated-macos-dev-setup.mdx
src/posts/using-generators-to-improve-developer-productivity.mdx
src/utils/api/blog/__tests__/__snapshots__/blog.spec.ts.snap

Hey! 👋🏼 
This PR adds a new blog post.

📝 Add dotfiles blog post
